"""Phase 5 proofs: the CISO report's LLM-authored executive summary
(src/foundry/reporter/executive_summary.py). Same "real call, deterministic
fallback underneath" shape as the Cartographer's FR-036a fallback and
Coverage-Guide's FR-073 checklist -- proven here via a scripted fake
`BaseChatModel`, the same technique test_orchestration_*.py already uses,
not a real OpenAI call (none available in this build environment).
"""
from __future__ import annotations

import pytest
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage
from langchain_core.outputs import ChatGeneration, ChatResult

from foundry.reporter.executive_summary import (
    RollupFacts,
    build_executive_summary,
    deterministic_executive_summary,
)


class ScriptedFakeModel(BaseChatModel):
    """Always answers with a fixed, clean paragraph -- proves the
    LLM-authored path is actually taken when a model is given and
    produces valid output."""

    reply: str = "The assessment found a small number of issues requiring prompt remediation."

    def _generate(self, messages, stop=None, run_manager=None, **kwargs) -> ChatResult:
        return ChatResult(generations=[ChatGeneration(message=AIMessage(content=self.reply))])

    async def _agenerate(self, messages, stop=None, run_manager=None, **kwargs) -> ChatResult:
        return self._generate(messages, stop, run_manager, **kwargs)

    @property
    def _llm_type(self) -> str:
        return "scripted-fake"


class RaisingFakeModel(BaseChatModel):
    """Simulates a real-world failure (bad key, network, timeout) -- the
    executive summary must still be produced, not raise."""

    def _generate(self, messages, stop=None, run_manager=None, **kwargs) -> ChatResult:
        raise RuntimeError("simulated model failure")

    async def _agenerate(self, messages, stop=None, run_manager=None, **kwargs) -> ChatResult:
        raise RuntimeError("simulated model failure")

    @property
    def _llm_type(self) -> str:
        return "raising-fake"


SAMPLE_FACTS = RollupFacts(
    total_findings=2,
    by_severity={"critical": 1, "medium": 1},
    exploited_count=1,
    not_exploited_count=1,
    component_count=2,
    closed_goal_count=1,
    open_goal_count=1,
    stop_reason="budget exhausted",
)

EMPTY_FACTS = RollupFacts(
    total_findings=0,
    by_severity={},
    exploited_count=0,
    not_exploited_count=0,
    component_count=0,
    closed_goal_count=0,
    open_goal_count=0,
    stop_reason="coverage complete",
)


# ---------------------------------------------------------------------------
# deterministic_executive_summary -- no LLM
# ---------------------------------------------------------------------------


def test_deterministic_summary_mentions_finding_count_and_worst_severity():
    text = deterministic_executive_summary(SAMPLE_FACTS)
    assert "2 confirmed finding" in text
    assert "critical" in text
    assert "[fallback]" in text


def test_deterministic_summary_handles_zero_findings():
    text = deterministic_executive_summary(EMPTY_FACTS)
    assert "no confirmed findings" in text.lower()


def test_deterministic_summary_always_mentions_stop_reason():
    assert "budget exhausted" in deterministic_executive_summary(SAMPLE_FACTS)


# ---------------------------------------------------------------------------
# build_executive_summary -- fails soft
# ---------------------------------------------------------------------------


async def test_no_model_uses_deterministic_summary():
    text = await build_executive_summary(SAMPLE_FACTS, None)
    assert "[fallback]" in text


async def test_real_model_call_is_used_when_it_succeeds():
    text = await build_executive_summary(SAMPLE_FACTS, ScriptedFakeModel())
    assert text == "The assessment found a small number of issues requiring prompt remediation."
    assert "[fallback]" not in text


async def test_model_failure_falls_back_to_deterministic_summary():
    text = await build_executive_summary(SAMPLE_FACTS, RaisingFakeModel())
    assert "[fallback]" in text


async def test_model_output_naming_the_provider_falls_back_to_deterministic():
    """FR-083 applies to this generated text exactly as it does to a
    published finding report -- a model that leaks its own identity gets
    discarded, not sanitized."""
    leaky_model = ScriptedFakeModel(reply="Generated by OpenAI's GPT model on localhost.")
    text = await build_executive_summary(SAMPLE_FACTS, leaky_model)
    assert "[fallback]" in text
    assert "openai" not in text.lower()


async def test_model_returning_empty_text_falls_back_to_deterministic():
    text = await build_executive_summary(SAMPLE_FACTS, ScriptedFakeModel(reply="   "))
    assert "[fallback]" in text
